# Generated by Django 5.0 on 2023-12-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='strategy',
            field=models.CharField(choices=[('5min ORB', '5min ORB'), ('S/R Break', 'S/R Break'), ('10/20 ema cross', '10/20 ema cross')], max_length=200),
        ),
    ]
